import type { Product, Category, Subcategory } from './types'

export const categories: Category[] = [
  {
    id: 'rails',
    name: 'Рельсы',
    slug: 'rails',
    description:
        'Железнодорожные, крановые и узкоколейные рельсы всех типов',
  },
  {
    id: 'sleepers',
    name: 'Шпалы и плиты',
    slug: 'sleepers',
    description:
        'Деревянные, железобетонные шпалы и подрельсовые плиты',
  },
  {
    id: 'fasteners',
    name: 'Крепёж',
    slug: 'fasteners',
    description:
        'Рельсовый крепёж: болты, гайки, накладки, скрепления',
  },
  {
    id: 'shoes',
    name: 'Башмаки',
    slug: 'shoes',
    description:
        'Тормозные и подкладочные башмаки для железнодорожных вагонов',
  },
  {
    id: 'buffers',
    name: 'Упоры тупиковые',
    slug: 'buffers',
    description:
        'Тупиковые упоры для защиты концов путей',
  },
  {
    id: 'metal',
    name: 'Металлоизделия',
    slug: 'metal',
    description:
        'Металлоизделия по чертежам заказчика',
  },
  {
    id: 'tools',
    name: 'Путевой инструмент',
    slug: 'tools',
    description:
        'Путевой инструмент: ручной и механизированный',
  },
]

export const subcategories: Subcategory[] = [
  {
    id: 'rails-new',
    name: 'Рельсы новые',
    categoryId: 'rails',
    categorySlug: 'rails',
    slug: 'new',
  },
  {
    id: 'rails-used',
    name: 'Рельсы б/у',
    categoryId: 'rails',
    categorySlug: 'rails',
    slug: 'used',
  },
  {
    id: 'rails-parts',
    name: 'Части рельсов',
    categoryId: 'rails',
    categorySlug: 'rails',
    slug: 'parts',
  },

  {
    id: 'sleepers-wood',
    name: 'Шпалы деревянные',
    categoryId: 'sleepers',
    categorySlug: 'sleepers',
    slug: 'wood',
  },
  {
    id: 'sleepers-concrete',
    name: 'Шпалы железобетонные',
    categoryId: 'sleepers',
    categorySlug: 'sleepers',
    slug: 'concrete',
  },
  {
    id: 'sleepers-plates',
    name: 'Плиты подрельсовые',
    categoryId: 'sleepers',
    categorySlug: 'sleepers',
    slug: 'plates',
  },

  {
    id: 'fasteners-bolts',
    name: 'Болты',
    categoryId: 'fasteners',
    categorySlug: 'fasteners',
    slug: 'bolts',
  },
  {
    id: 'fasteners-nuts',
    name: 'Гайки',
    categoryId: 'fasteners',
    categorySlug: 'fasteners',
    slug: 'nuts',
  },
  {
    id: 'fasteners-clamps',
    name: 'Скрепления',
    categoryId: 'fasteners',
    categorySlug: 'fasteners',
    slug: 'clamps',
  },

  {
    id: 'shoes-brake',
    name: 'Башмаки тормозные',
    categoryId: 'shoes',
    categorySlug: 'shoes',
    slug: 'brake',
  },
  {
    id: 'shoes-rail',
    name: 'Башмаки подкладочные',
    categoryId: 'shoes',
    categorySlug: 'shoes',
    slug: 'rail',
  },

  {
    id: 'buffers-concrete',
    name: 'Упоры бетонные',
    categoryId: 'buffers',
    categorySlug: 'buffers',
    slug: 'concrete',
  },
  {
    id: 'buffers-metal',
    name: 'Упоры металлические',
    categoryId: 'buffers',
    categorySlug: 'buffers',
    slug: 'metal',
  },

  {
    id: 'metal-sheets',
    name: 'Листы',
    categoryId: 'metal',
    categorySlug: 'metal',
    slug: 'sheets',
  },
  {
    id: 'metal-bars',
    name: 'Прутки',
    categoryId: 'metal',
    categorySlug: 'metal',
    slug: 'bars',
  },
  {
    id: 'metal-pipes',
    name: 'Трубы',
    categoryId: 'metal',
    categorySlug: 'metal',
    slug: 'pipes',
  },

  {
    id: 'tools-manual',
    name: 'Ручной инструмент',
    categoryId: 'tools',
    categorySlug: 'tools',
    slug: 'manual',
  },
  {
    id: 'tools-mechanized',
    name: 'Механизированный',
    categoryId: 'tools',
    categorySlug: 'tools',
    slug: 'mechanized',
  },
];

export const products: Product[] = [
  {
    id: 'rel-r65-new',
    slug: 'rel-r65-new',
    sku: 'REL-R65-N',
    title: 'Рельс Р-65 новый',
    gost: 'ГОСТ Р 51685-2022',
    weight: 64.72,
    length: 12.5,
    price: 68500,
    stock: 150,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'rails',
    subcategorySlug: 'new',
    description: 'Рельс железнодорожный новый типа Р-65 для главных путей.',
    specs: {
      'Тип': 'Р-65',
      'Длина': '12.5 м',
      'Масса 1 пог.м': '64.72 кг',
      'Сталь': 'Э76ХФ',
    },
  },
  {
    id: 'rel-r50-new',
    slug: 'rel-r50-new',
    sku: 'REL-R50-N',
    title: 'Рельс Р-50 новый',
    gost: 'ГОСТ Р 51685-2022',
    weight: 51.67,
    length: 12.5,
    price: 52000,
    stock: 200,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'rails',
    subcategorySlug: 'new',
    description: 'Рельс железнодорожный новый типа Р-50 для промышленных путей.',
    specs: {
      'Тип': 'Р-50',
      'Длина': '12.5 м',
      'Масса 1 пог.м': '51.67 кг',
      'Сталь': 'Э76ХФ',
    },
  },
  {
    id: 'rel-r75-new',
    slug: 'rel-r75-new',
    sku: 'REL-R75-N',
    title: 'Рельс Р-75 новый',
    gost: 'ГОСТ Р 51685-2022',
    weight: 74.41,
    length: 12.5,
    price: 82000,
    stock: 90,
    condition: 'new',
    images: ['/test-product.webp', '/test-product.webp'],
    categorySlug: 'rails',
    subcategorySlug: 'new',
    description: 'Рельс железнодорожный новый типа Р-75 для тяжелонагруженных путей.',
    specs: {
      'Тип': 'Р-75',
      'Длина': '12.5 м',
      'Масса 1 пог.м': '74.41 кг',
      'Сталь': 'Э76ХФ',
    },
  },
  {
    id: 'rel-r65-used',
    slug: 'rel-r65-used',
    sku: 'REL-R65-U',
    title: 'Рельс Р-65 б/у',
    gost: 'ГОСТ Р 51685-2022',
    weight: 64.72,
    length: 12.5,
    price: 35000,
    stock: 300,
    condition: 'used',
    images: ['/test-product.webp'],
    categorySlug: 'rails',
    subcategorySlug: 'used',
    description: 'Рельс железнодорожный б/у типа Р-65 после ревизии.',
  },
  {
    id: 'rel-r50-used',
    slug: 'rel-r50-used',
    sku: 'REL-R50-U',
    title: 'Рельс Р-50 б/у',
    gost: 'ГОСТ Р 51685-2022',
    weight: 51.67,
    length: 12.5,
    price: 28000,
    stock: 400,
    condition: 'used',
    images: ['/test-product.webp'],
    categorySlug: 'rails',
    subcategorySlug: 'used',
    description: 'Рельс железнодорожный б/у типа Р-50 для подъездных путей.',
  },
  {
    id: 'rel-r75-used',
    slug: 'rel-r75-used',
    sku: 'REL-R75-U',
    title: 'Рельс Р-75 б/у',
    gost: 'ГОСТ Р 51685-2022',
    weight: 74.41,
    length: 12.5,
    price: 43000,
    stock: 180,
    condition: 'used',
    images: ['/test-product.webp', '/test-product.webp'],
    categorySlug: 'rails',
    subcategorySlug: 'used',
    description: 'Рельс Р-75 б/у после дефектоскопии и ревизии.',
  },
  {
    id: 'rel-cut-r50',
    slug: 'rel-cut-r50',
    sku: 'REL-CUT-R50',
    title: 'Рельс резаный Р-50',
    gost: 'ГОСТ Р 51685-2022',
    weight: 51.67,
    length: 1,
    price: 4200,
    stock: 1000,
    condition: 'service',
    images: ['/test-product.webp'],
    categorySlug: 'rails',
    subcategorySlug: 'parts',
    description: 'Рельс Р-50, нарезанный на отрезки нужной длины.',
  },
  {
    id: 'rel-cut-r65',
    slug: 'rel-cut-r65',
    sku: 'REL-CUT-R65',
    title: 'Рельс резаный Р-65',
    gost: 'ГОСТ Р 51685-2022',
    weight: 64.72,
    length: 1,
    price: 5500,
    stock: 1200,
    condition: 'service',
    images: ['/test-product.webp'],
    categorySlug: 'rails',
    subcategorySlug: 'parts',
    description: 'Рельс Р-65, нарезанный на мерные отрезки.',
  },
  {
    id: 'rel-cut-r75',
    slug: 'rel-cut-r75',
    sku: 'REL-CUT-R75',
    title: 'Рельс резаный Р-75',
    gost: 'ГОСТ Р 51685-2022',
    weight: 74.41,
    length: 1,
    price: 6800,
    stock: 700,
    condition: 'service',
    images: ['/test-product.webp', '/test-product.webp'],
    categorySlug: 'rails',
    subcategorySlug: 'parts',
    description: 'Отрезки рельса Р-75 для ремонтных и строительных работ.',
  },

  {
    id: 'sleeper-wood-1',
    slug: 'sleeper-wood-1',
    sku: 'SLP-WD-1',
    title: 'Шпала деревянная тип 1',
    gost: 'ГОСТ 78-2011',
    weight: 70,
    length: 2.75,
    price: 1200,
    stock: 5000,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'sleepers',
    subcategorySlug: 'wood',
    description: 'Шпала деревянная пропитанная тип 1.',
  },
  {
    id: 'sleeper-wood-2',
    slug: 'sleeper-wood-2',
    sku: 'SLP-WD-2',
    title: 'Шпала деревянная тип 2',
    gost: 'ГОСТ 78-2011',
    weight: 65,
    length: 2.75,
    price: 950,
    stock: 7000,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'sleepers',
    subcategorySlug: 'wood',
    description: 'Шпала деревянная пропитанная тип 2.',
  },
  {
    id: 'sleeper-wood-bridge',
    slug: 'sleeper-wood-bridge',
    sku: 'SLP-WD-BR',
    title: 'Шпала деревянная мостовая',
    gost: 'ГОСТ 78-2011',
    weight: 82,
    length: 3,
    price: 1800,
    stock: 2500,
    condition: 'new',
    images: ['/test-product.webp', '/test-product.webp'],
    categorySlug: 'sleepers',
    subcategorySlug: 'wood',
    description: 'Усиленная деревянная шпала для мостовых и промышленных путей.',
  },
  {
    id: 'sleeper-concrete-sh1',
    slug: 'sleeper-concrete-sh1',
    sku: 'SLP-CN-SH1',
    title: 'Шпала Ш-1',
    gost: 'ГОСТ 19291-2019',
    weight: 270,
    length: 2.7,
    price: 4500,
    stock: 2000,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'sleepers',
    subcategorySlug: 'concrete',
    description: 'Шпала железобетонная Ш-1 для бесстыкового пути.',
  },
  {
    id: 'sleeper-concrete-sh2',
    slug: 'sleeper-concrete-sh2',
    sku: 'SLP-CN-SH2',
    title: 'Шпала Ш-2',
    gost: 'ГОСТ 19291-2019',
    weight: 275,
    length: 2.7,
    price: 4800,
    stock: 1800,
    condition: 'new',
    images: ['/test-product.webp', '/test-product.webp'],
    categorySlug: 'sleepers',
    subcategorySlug: 'concrete',
    description: 'Железобетонная шпала Ш-2 для железнодорожных путей.',
  },
  {
    id: 'sleeper-concrete-sh3',
    slug: 'sleeper-concrete-sh3',
    sku: 'SLP-CN-SH3',
    title: 'Шпала Ш-3',
    gost: 'ГОСТ 19291-2019',
    weight: 280,
    length: 2.7,
    price: 5200,
    stock: 1500,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'sleepers',
    subcategorySlug: 'concrete',
    description: 'Усиленная железобетонная шпала Ш-3.',
  },
  {
    id: 'plate-rc50',
    slug: 'plate-rc50',
    sku: 'PLT-RC50',
    title: 'Плита подрельсовая RC50',
    gost: 'ТУ 0941-001-44659632-2018',
    weight: 10,
    length: 0.5,
    price: 2400,
    stock: 12000,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'sleepers',
    subcategorySlug: 'plates',
    description: 'Плита подрельсовая полимеркомпозитная RC50.',
  },
  {
    id: 'plate-rc65',
    slug: 'plate-rc65',
    sku: 'PLT-RC65',
    title: 'Плита подрельсовая RC65',
    gost: 'ТУ 0941-001-44659632-2018',
    weight: 12,
    length: 0.5,
    price: 2800,
    stock: 10000,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'sleepers',
    subcategorySlug: 'plates',
    description: 'Плита подрельсовая полимеркомпозитная RC65.',
  },
  {
    id: 'plate-rc65-heavy',
    slug: 'plate-rc65-heavy',
    sku: 'PLT-RC65-H',
    title: 'Плита подрельсовая RC65 усиленная',
    gost: 'ТУ 0941-001-44659632-2018',
    weight: 14,
    length: 0.5,
    price: 3200,
    stock: 8000,
    condition: 'new',
    images: ['/test-product.webp', '/test-product.webp'],
    categorySlug: 'sleepers',
    subcategorySlug: 'plates',
    description: 'Усиленная подрельсовая плита RC65 для высоких нагрузок.',
  },

  {
    id: 'bolt-m22',
    slug: 'bolt-m22',
    sku: 'BLT-M22',
    title: 'Болт путевой М22',
    gost: 'ГОСТ 11530-93',
    weight: 0.4,
    length: 0.13,
    price: 150,
    stock: 60000,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'fasteners',
    subcategorySlug: 'bolts',
    description: 'Путевой болт М22 для рельсовых скреплений.',
  },
  {
    id: 'bolt-m24',
    slug: 'bolt-m24',
    sku: 'BLT-M24',
    title: 'Болт путевой М24',
    gost: 'ГОСТ 11530-93',
    weight: 0.45,
    length: 0.14,
    price: 180,
    stock: 50000,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'fasteners',
    subcategorySlug: 'bolts',
    description: 'Болт рельсового скрепления М24.',
  },
  {
    id: 'bolt-m27',
    slug: 'bolt-m27',
    sku: 'BLT-M27',
    title: 'Болт стыковой М27',
    gost: 'ГОСТ 11530-93',
    weight: 0.62,
    length: 0.16,
    price: 250,
    stock: 30000,
    condition: 'new',
    images: ['/test-product.webp', '/test-product.webp'],
    categorySlug: 'fasteners',
    subcategorySlug: 'bolts',
    description: 'Болт стыковой высокопрочный М27.',
  },
  {
    id: 'nut-m22',
    slug: 'nut-m22',
    sku: 'NUT-M22',
    title: 'Гайка М22',
    gost: 'ГОСТ 5915-70',
    weight: 0.06,
    length: 0.018,
    price: 35,
    stock: 120000,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'fasteners',
    subcategorySlug: 'nuts',
    description: 'Гайка шестигранная М22 оцинкованная.',
  },
  {
    id: 'nut-m24',
    slug: 'nut-m24',
    sku: 'NUT-M24',
    title: 'Гайка М24',
    gost: 'ГОСТ 5915-70',
    weight: 0.08,
    length: 0.02,
    price: 45,
    stock: 100000,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'fasteners',
    subcategorySlug: 'nuts',
    description: 'Гайка шестигранная М24 оцинкованная.',
  },
  {
    id: 'nut-m27',
    slug: 'nut-m27',
    sku: 'NUT-M27',
    title: 'Гайка М27',
    gost: 'ГОСТ 5915-70',
    weight: 0.1,
    length: 0.022,
    price: 65,
    stock: 80000,
    condition: 'new',
    images: ['/test-product.webp', '/test-product.webp'],
    categorySlug: 'fasteners',
    subcategorySlug: 'nuts',
    description: 'Усиленная шестигранная гайка М27.',
  },
  {
    id: 'clamp-kb',
    slug: 'clamp-kb',
    sku: 'CLP-KB',
    title: 'Скрепление КБ',
    gost: 'ГОСТ 19646-90',
    weight: 2.5,
    length: 0.3,
    price: 850,
    stock: 20000,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'fasteners',
    subcategorySlug: 'clamps',
    description: 'Скрепление раздельное промежуточное КБ.',
  },
  {
    id: 'clamp-kb65',
    slug: 'clamp-kb65',
    sku: 'CLP-KB65',
    title: 'Скрепление КБ-65',
    gost: 'ГОСТ 19646-90',
    weight: 2.7,
    length: 0.3,
    price: 920,
    stock: 18000,
    condition: 'new',
    images: ['/test-product.webp', '/test-product.webp'],
    categorySlug: 'fasteners',
    subcategorySlug: 'clamps',
    description: 'Промежуточное рельсовое скрепление КБ-65.',
  },
  {
    id: 'clamp-ars4',
    slug: 'clamp-ars4',
    sku: 'CLP-ARS4',
    title: 'Скрепление АРС-4',
    gost: 'ТУ 0921-001-01124323-2004',
    weight: 3.2,
    length: 0.3,
    price: 1250,
    stock: 15000,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'fasteners',
    subcategorySlug: 'clamps',
    description: 'Анкерное рельсовое скрепление АРС-4.',
  },

  {
    id: 'shoe-brake-cast',
    slug: 'shoe-brake-cast',
    sku: 'SHO-BR-C',
    title: 'Башмак тормозной чугунный',
    gost: 'ГОСТ 1101-93',
    weight: 38,
    length: 0.4,
    price: 4500,
    stock: 5000,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'shoes',
    subcategorySlug: 'brake',
    description: 'Башмак тормозной литой чугунный для грузовых вагонов.',
  },
  {
    id: 'shoe-brake-composite',
    slug: 'shoe-brake-composite',
    sku: 'SHO-BR-P',
    title: 'Башмак тормозной композитный',
    gost: 'ГОСТ Р 55093-2012',
    weight: 22,
    length: 0.4,
    price: 8900,
    stock: 3000,
    condition: 'new',
    images: ['/test-product.webp', '/test-product.webp'],
    categorySlug: 'shoes',
    subcategorySlug: 'brake',
    description: 'Башмак тормозной композиционный износостойкий.',
  },
  {
    id: 'shoe-brake-cast-heavy',
    slug: 'shoe-brake-cast-heavy',
    sku: 'SHO-BR-C-U',
    title: 'Башмак тормозной усиленный',
    gost: 'ГОСТ 1101-93',
    weight: 40,
    length: 0.42,
    price: 4900,
    stock: 4000,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'shoes',
    subcategorySlug: 'brake',
    description: 'Усиленный чугунный тормозной башмак.',
  },
  {
    id: 'shoe-rail-pad-kp',
    slug: 'shoe-rail-pad-kp',
    sku: 'SHO-PAD-KP',
    title: 'Подкладка КП',
    gost: 'ГОСТ 19646-90',
    weight: 4.2,
    length: 0.25,
    price: 650,
    stock: 40000,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'shoes',
    subcategorySlug: 'rail',
    description: 'Подкладка подрельсовая КП для деревянных шпал.',
  },
  {
    id: 'shoe-rail-pad-kr65',
    slug: 'shoe-rail-pad-kr65',
    sku: 'SHO-PAD-KR65',
    title: 'Подкладка КР-65',
    gost: 'ГОСТ 19646-90',
    weight: 4.5,
    length: 0.25,
    price: 720,
    stock: 35000,
    condition: 'new',
    images: ['/test-product.webp', '/test-product.webp'],
    categorySlug: 'shoes',
    subcategorySlug: 'rail',
    description: 'Подрельсовая подкладка КР-65.',
  },
  {
    id: 'shoe-rail-pad-2r',
    slug: 'shoe-rail-pad-2r',
    sku: 'SHO-PAD-2R',
    title: 'Подкладка двухребордчатая',
    gost: 'ГОСТ 19646-90',
    weight: 4.8,
    length: 0.26,
    price: 790,
    stock: 28000,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'shoes',
    subcategorySlug: 'rail',
    description: 'Двухребордчатая металлическая подкладка.',
  },

  {
    id: 'buffer-concrete-1',
    slug: 'buffer-concrete-1',
    sku: 'BUF-CN-1',
    title: 'Упор тупиковый бетонный',
    gost: 'ТУ 0941-002-44659632-2019',
    weight: 1500,
    length: 1.5,
    price: 45000,
    stock: 100,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'buffers',
    subcategorySlug: 'concrete',
    description: 'Упор тупиковый монолитный бетонный.',
  },
  {
    id: 'buffer-concrete-2',
    slug: 'buffer-concrete-2',
    sku: 'BUF-CN-UB1',
    title: 'Упор тупиковый УБ-1',
    gost: 'ТУ 0941-002-44659632-2019',
    weight: 1550,
    length: 1.5,
    price: 47000,
    stock: 80,
    condition: 'new',
    images: ['/test-product.webp', '/test-product.webp'],
    categorySlug: 'buffers',
    subcategorySlug: 'concrete',
    description: 'Сборный бетонный тупиковый упор УБ-1.',
  },
  {
    id: 'buffer-concrete-3',
    slug: 'buffer-concrete-3',
    sku: 'BUF-CN-UB2',
    title: 'Упор тупиковый УБ-2',
    gost: 'ТУ 0941-002-44659632-2019',
    weight: 1700,
    length: 1.6,
    price: 52000,
    stock: 60,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'buffers',
    subcategorySlug: 'concrete',
    description: 'Усиленный бетонный тупиковый упор УБ-2.',
  },
  {
    id: 'buffer-metal-1',
    slug: 'buffer-metal-1',
    sku: 'BUF-MT-1',
    title: 'Упор тупиковый металлический',
    gost: 'ТУ 0941-003-44659632-2020',
    weight: 800,
    length: 2,
    price: 85000,
    stock: 50,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'buffers',
    subcategorySlug: 'metal',
    description: 'Упор тупиковый сварной металлический с амортизатором.',
  },
  {
    id: 'buffer-metal-2',
    slug: 'buffer-metal-2',
    sku: 'BUF-MT-U',
    title: 'Упор тупиковый усиленный',
    gost: 'ТУ 0941-003-44659632-2020',
    weight: 950,
    length: 2.2,
    price: 105000,
    stock: 35,
    condition: 'new',
    images: ['/test-product.webp', '/test-product.webp'],
    categorySlug: 'buffers',
    subcategorySlug: 'metal',
    description: 'Усиленный металлический тупиковый упор.',
  },
  {
    id: 'buffer-metal-3',
    slug: 'buffer-metal-3',
    sku: 'BUF-MT-AM',
    title: 'Упор тупиковый амортизационный',
    gost: 'ТУ 0941-003-44659632-2020',
    weight: 1100,
    length: 2.2,
    price: 125000,
    stock: 25,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'buffers',
    subcategorySlug: 'metal',
    description: 'Металлический упор с усиленным амортизирующим механизмом.',
  },

  {
    id: 'sheet-steel-5',
    slug: 'sheet-steel-5',
    sku: 'SHT-ST-05',
    title: 'Лист стальной 5 мм',
    gost: 'ГОСТ 19903-2015',
    weight: 39.25,
    length: 2,
    price: 6500,
    stock: 800,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'metal',
    subcategorySlug: 'sheets',
    description: 'Лист горячекатаный стальной толщиной 5 мм.',
  },
  {
    id: 'sheet-steel-10',
    slug: 'sheet-steel-10',
    sku: 'SHT-ST-10',
    title: 'Лист стальной 10 мм',
    gost: 'ГОСТ 19903-2015',
    weight: 78.5,
    length: 2,
    price: 12000,
    stock: 500,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'metal',
    subcategorySlug: 'sheets',
    description: 'Лист горячекатаный стальной толщиной 10 мм.',
  },
  {
    id: 'sheet-steel-12',
    slug: 'sheet-steel-12',
    sku: 'SHT-ST-12',
    title: 'Лист стальной 12 мм',
    gost: 'ГОСТ 19903-2015',
    weight: 94.2,
    length: 2,
    price: 14500,
    stock: 350,
    condition: 'new',
    images: ['/test-product.webp', '/test-product.webp'],
    categorySlug: 'metal',
    subcategorySlug: 'sheets',
    description: 'Лист горячекатаный стальной толщиной 12 мм.',
  },
  {
    id: 'bar-steel-16',
    slug: 'bar-steel-16',
    sku: 'BAR-ST-16',
    title: 'Пруток стальной Ø16',
    gost: 'ГОСТ 2590-2006',
    weight: 1.58,
    length: 6,
    price: 3200,
    stock: 1500,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'metal',
    subcategorySlug: 'bars',
    description: 'Пруток круглый стальной диаметром 16 мм.',
  },
  {
    id: 'bar-steel-20',
    slug: 'bar-steel-20',
    sku: 'BAR-ST-20',
    title: 'Пруток стальной Ø20',
    gost: 'ГОСТ 2590-2006',
    weight: 2.47,
    length: 6,
    price: 4500,
    stock: 1000,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'metal',
    subcategorySlug: 'bars',
    description: 'Пруток круглый стальной диаметром 20 мм.',
  },
  {
    id: 'bar-steel-25',
    slug: 'bar-steel-25',
    sku: 'BAR-ST-25',
    title: 'Пруток стальной Ø25',
    gost: 'ГОСТ 2590-2006',
    weight: 3.85,
    length: 6,
    price: 6800,
    stock: 700,
    condition: 'new',
    images: ['/test-product.webp', '/test-product.webp'],
    categorySlug: 'metal',
    subcategorySlug: 'bars',
    description: 'Пруток круглый стальной диаметром 25 мм.',
  },
  {
    id: 'pipe-steel-32',
    slug: 'pipe-steel-32',
    sku: 'PIP-ST-32',
    title: 'Труба стальная Ø32',
    gost: 'ГОСТ 3262-75',
    weight: 3.6,
    length: 6,
    price: 5800,
    stock: 1200,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'metal',
    subcategorySlug: 'pipes',
    description: 'Труба водогазопроводная Ø32 мм.',
  },
  {
    id: 'pipe-steel-50',
    slug: 'pipe-steel-50',
    sku: 'PIP-ST-50',
    title: 'Труба стальная Ø50',
    gost: 'ГОСТ 3262-75',
    weight: 5.5,
    length: 6,
    price: 8500,
    stock: 800,
    condition: 'new',
    images: ['/test-product.webp', '/test-product.webp'],
    categorySlug: 'metal',
    subcategorySlug: 'pipes',
    description: 'Труба водогазопроводная Ø50 мм.',
  },
  {
    id: 'pipe-steel-108',
    slug: 'pipe-steel-108',
    sku: 'PIP-ST-108',
    title: 'Труба стальная Ø108',
    gost: 'ГОСТ 10704-91',
    weight: 12.5,
    length: 6,
    price: 15800,
    stock: 500,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'metal',
    subcategorySlug: 'pipes',
    description: 'Электросварная стальная труба Ø108 мм.',
  },

  {
    id: 'tool-hammer',
    slug: 'tool-hammer',
    sku: 'TL-HAM',
    title: 'Молоток путевой',
    gost: 'ТУ 12-06-39-2016',
    weight: 1.5,
    length: 0.35,
    price: 2500,
    stock: 200,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'tools',
    subcategorySlug: 'manual',
    description: 'Молоток путевой специальный.',
  },
  {
    id: 'tool-wrench',
    slug: 'tool-wrench',
    sku: 'TL-WRN',
    title: 'Ключ путевой',
    gost: 'ТУ 12-06-40-2016',
    weight: 3.2,
    length: 0.6,
    price: 4500,
    stock: 150,
    condition: 'new',
    images: ['/test-product.webp', '/test-product.webp'],
    categorySlug: 'tools',
    subcategorySlug: 'manual',
    description: 'Ключ путевой универсальный.',
  },
  {
    id: 'tool-crowbar',
    slug: 'tool-crowbar',
    sku: 'TL-CBR',
    title: 'Лом путевой усиленный',
    gost: 'ТУ 12-06-38-2016',
    weight: 5,
    length: 1.5,
    price: 3200,
    stock: 300,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'tools',
    subcategorySlug: 'manual',
    description: 'Усиленный лом для выполнения путевых работ.',
  },
  {
    id: 'tool-drill',
    slug: 'tool-drill',
    sku: 'TL-DRL',
    title: 'Сверлильная машина БМ-2А',
    gost: 'ТУ 12-06-41-2017',
    weight: 28,
    length: 0.8,
    price: 125000,
    stock: 20,
    condition: 'new',
    images: ['/test-product.webp', '/test-product.webp'],
    categorySlug: 'tools',
    subcategorySlug: 'mechanized',
    description: 'Машина сверлильная бензиновая для рельсов.',
  },
  {
    id: 'tool-grinder',
    slug: 'tool-grinder',
    sku: 'TL-GRN',
    title: 'Шлифмашина угловая',
    gost: 'ТУ 12-06-42-2017',
    weight: 12,
    length: 0.5,
    price: 85000,
    stock: 30,
    condition: 'new',
    images: ['/test-product.webp'],
    categorySlug: 'tools',
    subcategorySlug: 'mechanized',
    description: 'Машина шлифовальная бензиновая.',
  },
  {
    id: 'tool-rail-cutter',
    slug: 'tool-rail-cutter',
    sku: 'TL-CUT-RR',
    title: 'Рельсорезная машина РРМ-1',
    gost: 'ТУ 12-06-45-2017',
    weight: 32,
    length: 0.9,
    price: 145000,
    stock: 15,
    condition: 'new',
    images: ['/test-product.webp', '/test-product.webp', '/test-product.webp'],
    categorySlug: 'tools',
    subcategorySlug: 'mechanized',
    description: 'Бензиновая рельсорезная машина для резки рельсов.',
  },
]